#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="nginx"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting nginx $(nginx -V 2>&1 | head -n1 | cut -d / -f 2)"
exec nginx
