#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service defaults 10-nginx
SERVICE_NAME="nginx-config-reload"

check_container_initialized
check_service_initialized init
liftoff

while inotifywait -q -e create,delete,modify,attrib /etc/nginx/nginx.conf /etc/nginx/sites.enabled /etc/nginx/snippets/server.enabled "${NGINX_INCLUDE_CONFIGURATION}"; do
      print_info "Reloading Nginx configuration do to a detected change"
      nginx -s reload
      exit 0
done
