name: debian

on:
  workflow_call

jobs:
  build_debian:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        distro_variant: [ "trixie", "bookworm" ]
        image_variant:
          - core
          - faflopza
          - faflopzaze
    env:
      BASE_IMAGE: "ghcr.io/nfrastack/container-base"
      DISTRO: "debian"
      DISTRO_VARIANT: ${{ matrix.distro_variant }}
      IMAGE_VARIANT: ${{ matrix.image_variant }}
      ARCH: "linux/amd64,linux/arm64"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Download Encrypted Files
        uses: actions/download-artifact@v4
        with:
          name: encrypted-artifacts
          path: ./
      - name: Build Image
        uses: nfrastack/gha/.github/actions/build_multi_image@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

